fos_elastica:
  clients:
    default:
      host: '%env(ELASTICSEARCH_HOST)%'
      port: '%env(ELASTICSEARCH_PORT)%'
  indexes:
    category:
      index_name: category_%elasticsearch_suffix%
      types:
        category:
          persistence:
            driver: orm
            model: App\Entity\Category
            provider: null
            finder: null
            listener: null
          properties:
            id: { type: integer }
            code: { type: text }

    machine:
      index_name: machine_%elasticsearch_suffix%
      types:
        machine:
          persistence:
            driver: orm
            model: App\Entity\Machine
            provider: null
            finder: null
            listener: null
          properties:
            id: ~
            category:
              type: 'nested'
              properties:
                id: { type: integer }
                code: { type: text }
            agency:
              type: 'nested'
              properties:
                id: { type: integer }
                name: { type: text }
                agencyGeoPoint:
                    type: 'geo_point'
                operator:
                  type: 'nested'
                  properties:
                    email: { type: text }
                address:
                  type: 'nested'
                  properties:
                    geoPoint:
                      type: 'geo_point'
                    streetNumber: ~
                    streetName: ~
                    city: ~
                    country: ~
                    latitude: ~
                    longitude: ~



