vich_uploader:
  db_driver: orm
  mappings:
    slide_images:
      uri_prefix: /image/slides
      upload_destination: '%kernel.project_dir%/public/image/slides'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    product_images:
      uri_prefix: '/pdf/invoices'
      upload_destination: '%kernel.project_dir%/public/pdf/invoices'
